export const BUTTON_COUNT = 'BUTTON_COUNT';
export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const SEARCHED_ARTICLES = "SEARCHED_ARTICLES";
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const DOMAIN_PAGE_SELECTED = 'DOMAIN_PAGE_SELECTED';
export const OPENED_ARTICLE_CONTENT = 'OPENED_ARTICLE_CONTENT';
export const UNFAVORITE_ARTICLE = 'UNFAVORITE_ARTICLE';
